### ISSUE TITLE
torch.meanとtorch.stdで妙な挙動

### ISSUE THREAD

**Issue by tsugumi-sys** [tsugumi-sys/poteka-pipeline-pytorch#27]
### Problem

SequentialEvaliuatorの_update_input_tensorのテストで、実行側とテスト側（expect_tensor）のtorch.mean&stdの値が0.001くらい異なる。テストコードのテンソル生成をtorch.randではなくtorch.onesにするとパスする。

### Debug Output

```text
======================================================================
FAIL: test_update_input_tensor (tests.evaluate.test_sequential_evaluator.TestSequentialEvaluator) (scaling_method='standard', before_input_tensor_shape=torch.Size([1, 3, 18, 50, 50]), next_frame_tensor_shape=torch.Size([3, 35]))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/akira/akira/poteka-pipeline-pytorch/tests/evaluate/test_sequential_evaluator.py", line 75, in test_update_input_tensor
    self._test_update_input_tensor(scaling_method, before_input_tensor, before_standarized_info, next_frame_tensor)
  File "/home/akira/akira/poteka-pipeline-pytorch/tests/evaluate/test_sequential_evaluator.py", line 110, in _test_update_input_tensor
    self.assertEqual(standarized_info, expect_standarized_info)
AssertionError: {'rai[43 chars]0.1030)}, 'temperature': {'mean': tensor(0.018[83 chars]00)}} != {'rai[43 chars]0.1031)}, 'temperature': {'mean': tensor(0.018[83 chars]00)}}
  {'humidity': {'mean': tensor(0.0154), 'std': tensor(0.0900)},
-  'rain': {'mean': tensor(0.0186), 'std': tensor(0.1030)},
?                                                      ^

+  'rain': {'mean': tensor(0.0186), 'std': tensor(0.1031)},
?                                                      ^

-  'temperature': {'mean': tensor(0.0183), 'std': tensor(0.0986)}}
?                                                             ^

+  'temperature': {'mean': tensor(0.0183), 'std': tensor(0.0988)}}
?                                                             ^


======================================================================
FAIL: test_update_input_tensor (tests.evaluate.test_sequential_evaluator.TestSequentialEvaluator) (scaling_method='min_max_standard', before_input_tensor_shape=torch.Size([1, 3, 18, 50, 50]), next_frame_tensor_shape=torch.Size([3, 35]))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/akira/akira/poteka-pipeline-pytorch/tests/evaluate/test_sequential_evaluator.py", line 75, in test_update_input_tensor
    self._test_update_input_tensor(scaling_method, before_input_tensor, before_standarized_info, next_frame_tensor)
  File "/home/akira/akira/poteka-pipeline-pytorch/tests/evaluate/test_sequential_evaluator.py", line 110, in _test_update_input_tensor
    self.assertEqual(standarized_info, expect_standarized_info)
AssertionError: {'rai[43 chars]0.1030)}, 'temperature': {'mean': tensor(0.018[83 chars]00)}} != {'rai[43 chars]0.1031)}, 'temperature': {'mean': tensor(0.018[83 chars]00)}}
  {'humidity': {'mean': tensor(0.0154), 'std': tensor(0.0900)},
-  'rain': {'mean': tensor(0.0186), 'std': tensor(0.1030)},
?                                                      ^

+  'rain': {'mean': tensor(0.0186), 'std': tensor(0.1031)},
?                                                      ^

-  'temperature': {'mean': tensor(0.0183), 'std': tensor(0.0986)}}
?                                                             ^

+  'temperature': {'mean': tensor(0.0183), 'std': tensor(0.0988)}}
?                                                             ^
```
```


### Additional Context

_No response_

### References

_No response_

**Comment by tsugumi-sys** [comment]
Normalize　Tensorがなかったため
